### ISSUE TITLE
Add support for context store `state` object

### ISSUE THREAD

**Issue by erodewald** [SmartThingsCommunity/smartapp-sdk-nodejs#103]
**Is your feature request related to a problem? Please describe.**
The 2.0 dynamodb nodejs lib includes a new feature (addition of arbitrary `state` data object, and omission of `clientId`, `clientSecret`). The SDK needs to support this. 

**Describe the solution you'd like**
`endpoint-context.js` needs some functions to get/put this data whenever they want.

e.g.,
`getState()` : `Promise<object>`
`putState(state)` : `void`

**Describe alternatives you've considered**
`n/a`

**Additional context**
This needs to include unit tests, as we're already fighting abysmal code coverage numbers.

**Comment by erodewald** [comment]
PI-632

**Comment by rossiam** [comment]
Won't do. User can use their database directly.
