### ISSUE TITLE
More flexible API requests

### ISSUE THREAD

**Issue by erodewald** [SmartThingsCommunity/smartapp-sdk-nodejs#11]
**Is your feature request related to a problem? Please describe.**
I can't use async-await syntax with API calls. 

**Describe the solution you'd like**
To avoid 'callback hell', I would like to be able to use code like this:

```javascript
 try {
      const { data: unsub } = await ctx.api.subscriptions.unsubscribeAll();
      console.log(`Status: ${unsub.status}`)
      const { data: sub } = await ctx.api.subscriptions.subscribeToDevices(ctx.config.humiditySensors, "relativeHumidityMeasurement", "humidity", "humidityHandler");
      console.log(`Status: ${sub.status}`)
    } catch (err) {
      throw new Error(err)
    }
```

**Describe alternatives you've considered**
N/A

**Additional context**
It's not a cut-and-dry problem as there has been considerable thought put into making requests sequentially to abstract away complexities.

**Comment by bflorian** [comment]
@erodewald is this still an issue? I'm not sure about the returned values in these specific cases, but I've been using async / await with the current SDK extensively and not had a problem. What happens when you run the above code?

**Comment by bflorian** [comment]
The above code does now work, though the returned values are different in the 2.0 version of the SDK which uses the [SmartThings Core SDK](https://github.com/SmartThingsCommunity/smartthings-core-sdk) for API calls.
