### ISSUE TITLE
EXECUTE Lifecycle handler does not send response back to ST Cloud

### ISSUE THREAD

**Issue by unisist** [SmartThingsCommunity/smartapp-sdk-nodejs#121]
**Describe the bug**
To support private and future lifecycle events, we need to allow for a fall-through handler. This handler must pass what is needed to the implementation to respond to the event.

**To Reproduce**
Use service plugin at mobile client to request.

**Expected behavior**
Service plugin should receive response.

**Actual behavior**
Service plugin does not receive any response from ST Cloud.

**Additional context**
case 'EXECUTE': {
					this._log.event(evt)
					await this._executeHandler(context, evt.executeData)
					break
				}
handler in smart-app.js should send response use responder or pass responder object to custom executeHandler to respond at custom handler.

**Comment by bflorian** [comment]
Addressed in PR #141

**Comment by mnilyshome** [comment]
L
