### ISSUE TITLE
instanceof cannot check types in js

### ISSUE THREAD

**Issue by lukhong** [SmartThingsCommunity/smartapp-sdk-nodejs#123]
In schedules.js, sdk is checking types using `instanceof` but it is not working in JS.
It could be improved to use `isDate` or `isString` from underscore module.

	runDaily(name, time) {
		let date
		if (Array.isArray(time) && time[0].stringConfig) {
			date = new Date(time[0].stringConfig.value)
		} else if (time instanceof String) {
			date = new Date(time)
		} else if (time instanceof Date) {
			date = time

**Comment by bflorian** [comment]
Issue fixed in above mentioned PR
