### ISSUE TITLE
i18n for defaultValue of TextSetting

### ISSUE THREAD

**Issue by MJ17** [SmartThingsCommunity/smartapp-sdk-nodejs#125]
**Is your feature request related to a problem? Please describe.**

-> I'm developing a smartapp using this SDK. I'm trying to apply localization in my app. 
I tried to set default value of text setting applying i18n, but it doesn't seem to work.

**Describe the solution you'd like**

-> add some code in the constructor of TextSetting

**Describe alternatives you've considered**

-> or just do not support i18n. Show the same default message regardless of users' launguage setting.

**Additional context**

-> 
this._defaultValue = this.i18nKey('defaultValue')

**Comment by bflorian** [comment]
Issue resolved with above PR
