### ISSUE TITLE
question: Notifications API documentation

### ISSUE THREAD

**Issue by onderweg** [SmartThingsCommunity/smartapp-sdk-nodejs#135]
I'm happy to see, by looking at the source code, that there is a notification REST API available for SmartThings, that can be used to push notifications. Although  I can't find any documentation from Samsung about this API.

When using the notifications API, I receive notifications on my mobile devices via the SmartThings app, but not on my TV (whereas my TV does receive SmartThings notifications from for example my Smart washer).

So, my question is: is there more documentation available for the notifications API, other than is already available in the current SDK source code? T

Docs  might help diagnose why I won't receive notifications on my TV.

**Comment by bflorian** [comment]
@onderweg although certain Samsung appliances can directly send notifications to the TV, there isn't a general SmartThings platform feature to do that yet. For example, you cannot create rules to send notifications to the TV. If/when that functionality is provided as a general platform feature, such notifications should be possible from this API.
