### ISSUE TITLE
health event is not coming

### ISSUE THREAD

**Issue by jeesunhub** [SmartThingsCommunity/smartapp-sdk-nodejs#148]
**Describe the bug**
online/offline event is not coming after posting health subscription.

**To Reproduce**
1. call subscribeToDeviceHealth() to subscribe health
  public subscribeToDeviceHealth(subscriptionName: string): Promise<Subscription> {
        const path = `installedapps/${this.installedAppId()}/subscriptions`
        const body = {
            sourceType: SubscriptionSource.DEVICE_HEALTH,
            deviceHealth: {
                locationId: this.locationId(),
                subscriptionName,
            },
        }
        return this.client.post(path, body)
    }
2. check whether subscription is registered.
{
    "items": [
        {
            "id": "92723e9d-c96c-4890-bc59-554f00d3ee49",
            "installedAppId": "237d8be6-7588-4440-9f2e-b3b0789eb4f7",
            "sourceType": "DEVICE_HEALTH",
            "deviceHealth": {
                "deviceIds": [],
                "subscriptionName": "1a202a3d0c53d-45fb-b43d-71f140776912",
                "locationId": "6842c05b-5289-4039-a1ed-4d5017ec86a7"
            }
        }
    ],
    "_links": {}
}
3. turn off the device
4. wait the event 

**Expected behavior**
online/offline event should be called.

**Actual behavior**
nothing happened.

**Additional context**
TV, airconditional device are tested.
same result(nothing happened)

client id/secret is created with below command
POST /v1/apps HTTP/1.1
Host: api.smartthings.com
Authorization: Bearer {token}
Content-Type: application/json
Accept: application/json
cache-control: no-cache
Postman-Token: f494ae14-675e-42dd-97f6-68361296907f
{
  "appName": "test", 
    "singleInstance": false, 
    "displayName": "test", 
    "description": "test", 
    "appType": "API_ONLY", 
    "classifications":["AUTOMATION"], 
    "apiOnly": {
      "targetUrl": "https://a3166ba9.ngrok.io"},
    "oauth": {
      "clientName": "test", 
      "scope": ["l:devices","x:devices:*", "r:locations:*"], 
      "redirectUris": ["https://api.smartthings.com/oauth/callback", "https://localhost:8080/callback"
      ]
    }
}

DEVICE_LIFECYCLE is called.

**Comment by jeesunhub** [comment]
smartthings api provides 2 method to get health event. (use parameter as deviceIds OR locationId)
I tested this with deviceIds parameter. and this does not return health event as well.
https://smartthings.developer.samsung.com/docs/api-ref/st-api.html#operation/saveSubscription
Both are failed.

@bflorian 
I hoe you share the progress if you find something.

**Comment by Kwanghyuk-Kim** [comment]
I happen to meet the similar issue too.

@bflorian 
is there good way to see the DEVICE HEALTH event for samsung TV ?

**Comment by bflorian** [comment]
@Kwanghyuk-Kim @jeesunhub I've been able to reproduce this problem. It seems to be an issue in the platform, not this SDK. I'm escalating to the proper platform teams.

**Comment by bflorian** [comment]
The problem has been identified. A fix should be deployed next week. No update to the SDK will be necessary

**Comment by bflorian** [comment]
Verified that device health events are again being received.
