### ISSUE TITLE
For aws lambda, can't receive CONFIGURATION event's PAGE phase when smartapp has permissions

### ISSUE THREAD

**Issue by deokjinkim** [SmartThingsCommunity/smartapp-sdk-nodejs#152]
**Describe the bug**
For aws lambda, can't receive CONFIGURATION event's PAGE phase when smartapp has permissions

**To Reproduce**
1. Create smartapp based on smartapp-sdk-nodejs(version : 2.2.0)
2. Upload source code(including node_modules) to aws lambda
3. Grant permission to smartthings for invoking lambda function
4. Register lambda function with smartthings
5. Test using smartthings app
 Add device => My testing devices => Select smartapp(lambda version) => Select location and room and press 'Next'

**Expected behavior**
Lambda function should receive CONFIGURATION event's PAGE phase.

**Actual behavior**
Lambda function receive CONFIGURATION event's INITIALIZE phase, but can't receive PAGE phase.

**Additional context**
If smartapp doesn't have permission, lambda function can receive PAGE phase.
Below is my source code with permission.
```
//index.js
'use strict'

const SmartApp = require('@smartthings/smartapp')
const permission = ['r:devices:*', 'w:devices:*', 'i:deviceprofiles']

const smartapp = new SmartApp()
  .enableEventLogging(2)
  .permissions(permission) // Without this line, it's working
  .page('mainPage', (context, page, configData) => {
    page.section('sensors', section => {
      section
        .deviceSetting('contactSensor')
        .capabilities(['contactSensor'])
        .required(false)
    })
  })
  .updated(async (context, updateData) => {
    await context.api.subscriptions.unsubscribeAll()
    return context.api.subscriptions.subscribeToDevices(context.config.contactSensor, 'contactSensor', 'contact', 'myDeviceEventHandler')
  })
  .subscribedEventHandler('myDeviceEventHandler', (context, event) => {
    const value = event.value === 'open' ? 'on' : 'off'
    context.api.devices.sendCommands(context.config.lights, 'switch', value)
  })

exports.handler = (event, context, callback) => {
  smartapp.handleLambdaCallback(event, context, callback)
}
```

**Comment by bflorian** [comment]
@deokjinkim if you are explicitly setting permissions with `.permissions()` you also need to set the app ID with `appId()`. For example:
```
	.appId('585f80a9-21cf-4c01-bd88-d2e87af60ae4')
	.permissions(['i:deviceprofiles:*'])
```

As a side note, if your app is only a C2C connector, that is, if it only creates devices and handles device commands, then you only need the `i:deviceprofiles:*` scope. You do not need the `r:devices:*` and `w:devices:*` for your app to access the devices that it creates. You only need those scopes to read and modify other devices, that your app has not created. 

The documentation is wrong in this regard. I'll create a ticket to have it corrected. Apologies for the confusion.

**Comment by bflorian** [comment]
I'm closing this issue under the assumption that explicitly setting the permissions corrected it. Please re-open if that is not the case.
