### ISSUE TITLE
question: support async event handler function for lambda

### ISSUE THREAD

**Issue by deokjinkim** [SmartThingsCommunity/smartapp-sdk-nodejs#159]
**What is your question? Please describe.**
Because now handleLambdaCallback is not async function, so we have to use callback(3rd parameter of event handler function) for response. But we usually will need async operation(get partner cloud's device list, initialize db, and so on) for event handler function of lambda. 

When I checked, schema connector's lambda function is already supported async handleLambdaCallback function. (https://github.com/SmartThingsCommunity/st-schema-nodejs/blob/aa27c273fea448ea4123a104257d30ce5d5ac09e/lib/SchemaConnector.js#L155)

Do you have any plan for 'async event handler function' for lambda support on smartapp-sdk-nodejs?

**Additional context**

**Comment by bflorian** [comment]
Yes, we'll take a look at that. I agree that requiring use of callback is not a best practice.

**Comment by bflorian** [comment]
Fix made and published to NPM @deokjinkim
