### ISSUE TITLE
imageSetting does not support height and width

### ISSUE THREAD

**Issue by rym002** [SmartThingsCommunity/smartapp-sdk-nodejs#201]
**Is your feature request related to a problem? Please describe.**
Examples provided https://smartthings.developer.samsung.com/docs/tutorials/how-to/design-pages-smartapp.html#Image-Setting show height and width can be specified on an image. The imageSettings does not support these values.

**Describe the solution you'd like**
add height and width to imageSettings

**Describe alternatives you've considered**
None

**Additional context**

**Comment by john-u** [comment]
@rym002 I have found that the doc section you linked above is simply incorrect. Image Setting does not define height or width properties on our platform, thus adding these in the SDK will not have any effect. CSS styles automatically control the visual height and width of images with a responsive design approach.

Sorry for the confusion. We will follow up with respective teams about updating the docs to correct the issue.

**Comment by john-u** [comment]
We have officially announced our new doc portal were we have addressed this issue with the [image setting section](https://developer-preview.smartthings.com/docs/connected-services/configuration#image-setting). Thanks for bringing this to our attention and please continue to do so!
