### ISSUE TITLE
Starter: AWS serverless support

### ISSUE THREAD

**Issue by erodewald** [SmartThingsCommunity/smartapp-sdk-nodejs#28]
**Is your feature request related to a problem? Please describe.**
When developing, it can be difficult to switch between local and cloud deployments. 

**Describe the solution you'd like**
It would be nice to add some means to easily deploy to cloud infrastructure. Many configurations could be available which would auto-implement the basics and ask for AWS keys/secrets during the wizard. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by erodewald** [comment]
I have started a project that might be better suited to solve this ... https://github.com/SmartThingsCommunity/generator-smartthings-smartapp

**Comment by bflorian** [comment]
The original request for an example is available here https://github.com/SmartThingsCommunity/smartapp-example-no-devices-nodejs-lambda
