### ISSUE TITLE
Split API from SmartApp SDK

### ISSUE THREAD

**Issue by erodewald** [SmartThingsCommunity/smartapp-sdk-nodejs#29]
**Is your feature request related to a problem? Please describe.**
As a developer of a non-SmartApp related project, I want to easily make API calls without using the smartapp sdk. 

**Describe the solution you'd like**
Create a standalone NPM package that makes API calls only. 

**Describe alternatives you've considered**

**Additional context**
The outcome (standalone project) can be consumed by this project in turn. This can stabilize and simplify this project.

**Comment by bflorian** [comment]
Done in PR #143 . API calls are now handled by the [SmartThings Core SDK](https://github.com/SmartThingsCommunity/smartthings-core-sdk).
