### ISSUE TITLE
appId sometimes required

### ISSUE THREAD

**Issue by erodewald** [SmartThingsCommunity/smartapp-sdk-nodejs#34]
**Describe the bug**
> However, as separate issue also needed to add the `.appId("string")` when using `.permission(...)` Without this Mobile App will report the generic "Network Error has occurred" when attempting the Configuration Lifecycle.

> What is interesting is I put a random value here for `.appId("random")` and it still worked, so unsure this functionality and purpose.
```smartapp
  .appId('nodejs-sdk-example')
  .publicKey('@./smartthings_rsa.pub') // optional until app verified
  .configureI18n()
  .permissions(['i:deviceprofiles'])
  .page('mainPage', (context, page, configData) => {
```

**To Reproduce**
1. Create smartapp
2. do not set `appId()`
3. set `permissions()`
4. Have configuration pages
5. Try to use the configuration in oneapp
6. See error

**Expected behavior**
Not setting appId() should not break the app by setting a default name

**Actual behavior**
Mobile app breaks when not setting it

**Screenshots**
n/a

**Environment (please complete the following information):**
n/a

**Additional context**
reported by @jonathanpaek, please comment if I got anything wrong here

**Comment by jodyalbritton** [comment]
Unable to reproduce.
