### ISSUE TITLE
Refresh Token does not encode its body

### ISSUE THREAD

**Issue by Laptopmini** [SmartThingsCommunity/smartapp-sdk-nodejs#35]
**Describe the bug**
When making a request to refresh the token, the client id, secret and refreshToken are not encoded which may result in errors.

```js
grant_type=refresh_token&client_id=${encodeURIComponent(clientId)}&client_secret=${encodeURIComponent(clientSecret)}&refresh_token=${encodeURIComponent(refreshToken)}
```

**Comment by erodewald** [comment]
@jodyalbritton I think we can close this – do you have permission? If not I'll make sure you get it.

**Comment by jodyalbritton** [comment]
Closed as no repro
