### ISSUE TITLE
include tooling to facilitate proper commit messages

### ISSUE THREAD

**Issue by rossiam** [SmartThingsCommunity/smartapp-sdk-nodejs#42]
**Is your feature request related to a problem? Please describe.**
We have added semantic versioning and now require commit messages to be properly formed.

**Describe the solution you'd like**
Include a tool like semantic-git-commit-cli to help generate properly-formed commit messages.

**Describe alternatives you've considered**
We could update the commit messages for the committer on merge.

**Additional context**
none

**Comment by erodewald** [comment]
This issue was note closed properly – resolved by #43
