### ISSUE TITLE
Device API's mentions of getState() is inconsistent

### ISSUE THREAD

**Issue by erodewald** [SmartThingsCommunity/smartapp-sdk-nodejs#64]
**Is your feature request related to a problem? Please describe.**
The actual API refers to `status`, but the SDK calls it `state`, which could (for all intents and purposes) be an entirely different feature. 

**Describe the solution you'd like**
Rename "device state" mentions and function names to "status". 

**Describe alternatives you've considered**
~~

**Additional context**
https://github.com/SmartThingsCommunity/smartapp-sdk-nodejs/blob/master/lib/platform/devices.js#L77-L79

https://github.com/SmartThingsCommunity/smartapp-sdk-nodejs/blob/master/lib/platform/devices.js#L81-L83

https://github.com/SmartThingsCommunity/smartapp-sdk-nodejs/blob/master/lib/platform/devices.js#L85-L87

**Comment by bflorian** [comment]
This issue is addressed in the 2.0 version with the change to the [SmartThings Core SDK](https://github.com/SmartThingsCommunity/smartthings-core-sdk), though the old getState methods are still present (though deprecated) to minimize breaking changes
