### ISSUE TITLE
keys duplicating in I18n `/locales/en.json` file after app restart

### ISSUE THREAD

**Issue by jonathanpaek** [SmartThingsCommunity/smartapp-sdk-nodejs#9]
**Describe the bug**
This is regarding the`/locales/en.json` file which is used for localization of the configuration lifecycle.   Upon restarting nodejs app there are new (duplicate) keys being appended in the file.

Example:

The last entry here `pages.mainPage.sections.lights.name` was duplicated after restarting the nodejs app.

```
{
	"pages.mainPage.name": "Nodejs Sample SmartApp - Let there be Light",
	"pages.mainPage.settings.lights.name": "Select lights  and  switches",
	"Tap to set": "Select Devices",
	"pages.mainPage.sections.lights.name": "pages.mainPage.sections.lights.name"
}
```

**To Reproduce**
1. Build app using the codesnip available in readme (for endpointapp) or include the following codesnip ...

```
smartapp.publicKey(`@./smartthings_rsa.pub`)
    .configureI18n()
    .page('mainPage', (response, page) => {
        page.section('lights', (section) => {
            section.deviceSetting('lights').capabilities(['switch']).multiple(true).permissions('rx');
        });
    })
```

2. Run through SmartApp Installation using SmartThings mobile app (this will generate the file 1st time round.

3. Observe file is generated `locales/en.json`.   Then restart the nodejs app and repeat above steps.  

4. Observe file again `locales/en.json`and note the keys duplicated per description.

**Expected behavior**
File should not be modified:
```
{
	"pages.mainPage.name": "Nodejs Sample SmartApp - Let there be Light",
	"pages.mainPage.settings.lights.name": "Select lights  and  switches",
	"Tap to set": "Select Devices",
}
```

**Actual behavior**
Duplicate key is added
```
{
	"pages.mainPage.name": "Nodejs Sample SmartApp - Let there be Light",
	"pages.mainPage.settings.lights.name": "Select lights  and  switches",
	"Tap to set": "Select Devices",
	"pages.mainPage.sections.lights.name": "pages.mainPage.sections.lights.name"
}
```

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by erodewald** [comment]
More observations on this:

* the i18n pkg, by default, does not generate the keys/values. That is enabled / disabled by `opts = { updateFiles: true }`. Perhaps we should default that to false. 
* if you reorder any of the keys, it will blow away your keys/values. it seems that not reordering things may allow existing values to persist. Still feeling uneasy about it. 

Possible fix is to just disable `updateFiles` by default and let devs opt into it, making them aware of the fact that the file is quite volatile and they need to keep those string values safe.

**Comment by bflorian** [comment]
@erodewald I have not been able to this problem by simply re-ordering the keys, as long as the file is valid JSON. However any JSON error, including a dangling comma on the last line, causes the file to be blown away. Do you have a reproducible example where just re-ordering, but with a valid JSON file, causes the problem?

It is very fragile and defaulting to updateFiles:false seems like a good idea. I might also look at checking the files for validity during startup. But if there is a case where just re-ordering while maintaining a valid JSON file causes the problem, then that may not be worth the effort

**Comment by bflorian** [comment]
Version 2.0.0 of the SDK changed the default setting to `updateFiles: false`. Have not been able to reproduce the duplicate entries other than in cases of corrupted JSON files. Added an SDK backlog item to pre-validate files with update option is enabled.

**Comment by rossiam** [comment]
One issue with the JSON file being overwritten completely when it was Invalid has been resolved.

Cannot reproduce duplicate key issues.
